# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'UserNotificaion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UserNotificaion
  pod 'AFNetworking', '~> 3.0'
  pod 'IQKeyboardManager', '~> 6.2.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'MBProgressHUD'

end
