# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ThirdPartySDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThirdPartySDK
  pod 'FBSDKLoginKit'

  target 'ThirdPartySDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThirdPartySDKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
