# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ThirdPartySDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThirdPartySDK
  pod 'FBSDKLoginKit'
  pod 'AFNetworking', '~> 3.0'
  pod 'IQKeyboardManager', '~> 6.2.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'MBProgressHUD'

  target 'ThirdPartySDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThirdPartySDKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
